# Generated by Django 5.2.6 on 2026-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_user_id', models.CharField(max_length=64, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('access_token', models.TextField(editable=False)),
                ('refresh_token', models.TextField(editable=False)),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('requires_reauthorization', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Twitch connection',
                'verbose_name_plural': 'Twitch connections',
                'ordering': ('-updated_at',),
            },
        ),
    ]
