# Generated by Django 5.2.6 on 2026-09-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_stream_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('category_id', models.CharField(blank=True, max_length=64)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('is_mature', models.BooleanField(default=False)),
                ('last_viewer_count', models.PositiveIntegerField(default=0)),
                ('last_observed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to='streamers.streamer')),
            ],
            options={
                'ordering': ('-started_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'live')), fields=('streamer',), name='unique_live_session_per_streamer')],
            },
        ),
    ]
