# Generated by Django 5.2.6 on 2026-09-04 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_event_message_id', models.CharField(max_length=128, unique=True)),
                ('twitch_message_id', models.CharField(max_length=128, unique=True)),
                ('chatter_user_id_hash', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('emote_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='monitoring.streamsession')),
            ],
            options={
                'ordering': ('timestamp',),
                'indexes': [models.Index(fields=['session', 'timestamp'], name='chat_session_time_idx')],
            },
        ),
    ]
