# Generated by Django 5.2.6 on 2026-09-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_clip_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('twitch_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('twitch_created_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, choices=[('twitch_create_rejected', 'Twitch rejected the clip request'), ('twitch_auth_failed', 'Twitch would not authorize the request'), ('twitch_create_malformed', 'Twitch returned an unusable response'), ('verification_timeout', 'The clip did not appear in time'), ('verification_failed', 'The clip could not be verified'), ('broadcaster_mismatch', "Twitch returned another channel's clip"), ('request_state_unknown', "The request's outcome is unknown")], default='', max_length=32)),
                ('failure_detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clip', to='moments.momentcandidate')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
