# Generated by Django 5.2.6 on 2026-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch')], default='twitch', max_length=32)),
                ('platform_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('channel_url', models.URLField(max_length=500)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('broadcaster_type', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('username',),
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='unique_streamer_platform_account'), models.UniqueConstraint(fields=('platform', 'username'), name='unique_streamer_platform_username')],
            },
        ),
    ]
