# Generated by Django 5.2.6 on 2026-09-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('current_window_start', models.DateTimeField()),
                ('current_window_end', models.DateTimeField()),
                ('baseline_window_start', models.DateTimeField()),
                ('baseline_window_end', models.DateTimeField()),
                ('current_message_count', models.PositiveIntegerField()),
                ('baseline_message_count', models.PositiveIntegerField()),
                ('current_unique_chatters', models.PositiveIntegerField()),
                ('baseline_unique_chatters', models.PositiveIntegerField()),
                ('current_emote_count', models.PositiveIntegerField()),
                ('baseline_emote_count', models.PositiveIntegerField()),
                ('current_reaction_count', models.PositiveIntegerField()),
                ('baseline_reaction_count', models.PositiveIntegerField()),
                ('velocity_ratio', models.FloatField()),
                ('velocity_score', models.FloatField()),
                ('reaction_score', models.FloatField()),
                ('emote_score', models.FloatField()),
                ('diversity_score', models.FloatField()),
                ('absolute_activity_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('clip_requested', 'Clip requested'), ('clip_created', 'Clip created'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='detected', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moment_candidates', to='monitoring.streamsession')),
            ],
            options={
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['session', 'detected_at'], name='moment_session_time_idx')],
            },
        ),
    ]
